//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanify_Playlist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int SongID { get; set; }
        public string SongName { get; set; }
        public string Artist { get; set; }
        public int Plays { get; set; }
        public int LengthInSec { get; set; }
        public string AlbumName { get; set; }
        public int PlaylistID { get; set; }
    
        public virtual Playlist Playlist { get; set; }
    }
}
